const { chromium } = require('playwright');
const path = require('path');

(async () => {
  const browser = await chromium.launch({headless: true, channel: 'chrome'});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', err => errors.push(err.message));
  const origin = 'http://127.0.0.1:8765';
  await page.goto(origin);
  await page.locator('#run-list').waitFor();
  await page.locator('#new-run').click();
  const modes = await page.locator('#mode option').evaluateAll(options => options.map(option => option.value));
  if (modes.join(',') !== 'mock_mixed,live') throw new Error('Unexpected modes: ' + modes.join(','));
  const scopes = await page.locator('#scope option').evaluateAll(options => options.map(option => option.value));
  if (scopes.join(',') !== 'sequential10,random10,custom,all') throw new Error('Unexpected scope options: ' + scopes.join(','));
  if (await page.locator('#scope-fields').isVisible()) throw new Error('Mock mode should not show question scope');
  await page.locator('#mode').selectOption('live');
  if (!(await page.locator('#scope-fields').isVisible())) throw new Error('Live mode should show question scope');
  if (await page.locator('#scope').inputValue() !== 'sequential10') throw new Error('Live scope not sequential 10');
  await page.locator('#mode').selectOption('mock_mixed');
  if (await page.locator('#scope-fields').isVisible()) throw new Error('Mock mode showed question scope after switching back');
  await page.locator('#confirm').click();
  await page.waitForURL('**/runs/*');
  await page.locator('#case-table tr[data-id]').first().waitFor();
  await page.waitForFunction(() => document.querySelector('#run-meta').textContent.includes('已完成'));
  if (await page.locator('#metric-cards .card').count() !== 3) throw new Error('Expected three primary metrics');
  if (await page.locator('#status-summary .status-count').count() !== 4) throw new Error('Expected four result counts');
  if (await page.locator('#dimension-metrics .dim-metric').count() !== 7) throw new Error('Expected seven compact diagnostic metrics');
  const primaryIssues = await page.locator('#primary-issues').textContent();
  if (!primaryIssues.includes('主要问题')) throw new Error('Missing primary issue summary');
  const headers = await page.locator('#case-table th').allTextContents();
  if (!headers.includes('主要问题')) throw new Error('Missing primary issue column');
  await page.screenshot({path: path.resolve('runtime/ui-desktop.png'), fullPage: true});

  await page.locator('#case-table tr[data-id]').first().click();
  await page.locator('#verdict-qualified').waitFor();
  if (await page.locator('#verdict-unqualified').count() !== 1 || await page.locator('#verdict-unevaluable').count() !== 1) throw new Error('Missing verdict buttons');
  if (await page.locator('#evidence .pane').count() !== 2) throw new Error('Expected Agent and SQL result panes');
  await page.locator('#agent-result').waitFor({state: 'visible'});
  const questionFont = parseFloat(await page.locator('#case-question').evaluate(element => getComputedStyle(element).fontSize));
  if (questionFont < 20) throw new Error('Question text is not prominent enough');
  const evidencePanes = await page.locator('#evidence .pane').evaluateAll(elements => elements.map(element => ({width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height})));
  if (Math.abs(evidencePanes[0].width - evidencePanes[1].width) > 1 || Math.abs(evidencePanes[0].height - evidencePanes[1].height) > 1) throw new Error('Agent and SQL result panes are not equal size');
  const agentOverflow = await page.locator('#agent-result').evaluate(element => getComputedStyle(element).overflowY);
  if (agentOverflow !== 'auto') throw new Error('Agent result pane is not scrollable');
  if (await page.locator('#tab-diff .llm-dim').count() !== 7) throw new Error('Expected seven dimensions in result comparison');
  await page.locator('#sql-result table').waitFor({state: 'visible'});
  if (await page.locator('.tabs [data-tab]').count() !== 5) throw new Error('Expected five detail tabs');
  await page.locator('[data-tab=agent]').click();
  if (await page.locator('#tab-agent .payload-code').count() !== 2) throw new Error('Expected raw request and response payloads');
  const payloadSizes = await page.locator('#tab-agent .payload-code').evaluateAll(elements => elements.map(element => ({width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height, overflowY: getComputedStyle(element).overflowY})));
  if (Math.abs(payloadSizes[0].width - payloadSizes[1].width) > 1 || Math.abs(payloadSizes[0].height - payloadSizes[1].height) > 1) throw new Error('Raw payload boxes are not equal size');
  if (payloadSizes.some(size => size.overflowY !== 'auto')) throw new Error('Raw payload boxes are not scrollable');
  await page.screenshot({path: path.resolve('runtime/ui-case-agent-desktop.png'), fullPage: true});
  await page.locator('[data-tab=caliber]').click();
  if (await page.locator('#tab-caliber .caliber-table tbody tr').count() < 1) throw new Error('Caliber alignment rows missing');
  const caliberText = await page.locator('#tab-caliber').textContent();
  if (caliberText.includes('智能体值') || caliberText.includes('SQL值') || caliberText.includes('结果')) throw new Error('Caliber tab duplicates comparison details');
  await page.screenshot({path: path.resolve('runtime/ui-case-caliber-desktop.png'), fullPage: true});
  await page.locator('[data-tab=sql]').click();
  if (await page.locator('#tab-sql .sql-param-input').count() < 1) throw new Error('Editable SQL parameters missing');
  const queryHeight = await page.locator('#sql-recheck-query').evaluate(element => element.getBoundingClientRect().height);
  if (queryHeight > 170) throw new Error('SQL recheck box was not reduced');
  await page.screenshot({path: path.resolve('runtime/ui-case-sql-desktop.png'), fullPage: true});
  await page.locator('[data-tab=diff]').click();
  await page.screenshot({path: path.resolve('runtime/ui-case-desktop.png'), fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: path.resolve('runtime/ui-case-mobile.png'), fullPage: true});
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  if (overflow) throw new Error('Mobile document overflow');
  await page.setViewportSize({width: 1440, height: 1000});
  await page.locator('[data-tab=logs]').click();
  await page.locator('#tab-logs.active').waitFor();
  await page.setViewportSize({width: 390, height: 844});
  await page.goto(origin);
  await page.locator('#new-run').click();
  await page.locator('#mode').selectOption('live');
  await page.screenshot({path: path.resolve('runtime/ui-dialog-mobile.png'), fullPage: true});
  if (errors.length) throw new Error(errors.join('\n'));
  console.log(JSON.stringify({ok: true, screenshots: 7, mobile_overflow: overflow}));
  await browser.close();
})().catch(err => { console.error(err); process.exit(1); });
