# -*- coding: utf-8 -*-
"""141 道单 Query 元数据。题面逐字来自方案文档；
JL-026~JL-035 为维修工单基础统计（期间=create_time 半开区间）。
CX-036/037、DMA-026、JL-036、BJ-016 为 2026-09-21 补录业务核对过的 25 题（Q1/Q3/Q28/Q30/Q19）。"""


def _m(key, col, unit, scale, **extra):
    rec = {"key": key, "sql_column": col, "unit": unit, "value_scale": scale}
    rec.update(extra)
    return rec


def pct(key, col="rate", **extra):
    # value_scale 描述存储形态：SQL 按标准集规则输出 0-1 小数比值（禁止 *100），黄金集只存原始值；
    # unit 是业务单位（评测端做 ratio01→% 的口径对齐），不是对存储值的标注。
    return _m(key, col, "%", "ratio01", **extra)


def vol(key, col, **extra):
    return _m(key, col, "m³", "volume", **extra)


def cnt(key, col, **extra):
    return _m(key, col, "count", "count", **extra)


def pp(key, col, **extra):
    # 差值/同比/环比同样存 0-1 小数形式（两个比值之差），×100 后为 pp。
    return _m(key, col, "pp", "ratio01", **extra)


def hour(key, col, **extra):
    return _m(key, col, "h", "volume", **extra)


def per_km(key, col, **extra):
    return _m(key, col, "单/km", "volume", **extra)


def C(case_id, question, category, indicator_type, result_type, builder, resolver,
      org_scope, time_scope_raw, org_scope_raw, caliber, measures, row_key=None, **extra):
    rec = {
        "case_id": case_id,
        "question": question,
        "category": category,
        "scene_big": {
            "CX": "产销差率与供水售水量",
            "LS": "供水管网漏损率与综合漏损",
            "DMA": "小区DMA与漏损分级管控",
            "JL": "探漏效率与管网维抢修工单",
            "BJ": "异常报警处置与管网设施健康",
        }[category],
        "indicator_type": indicator_type,
        "result_type": result_type,
        "builder": builder,
        "parameter_resolver": resolver,
        "org_scope": org_scope,
        "row_key": row_key or [],
        "measures": measures,
        "time_scope_raw": time_scope_raw,
        "org_scope_raw": org_scope_raw,
        "caliber": caliber,
        "numeric_evaluable": extra.get("numeric_evaluable", True),
        "business_verified": case_id in BUSINESS_VERIFIED_IDS,
        "roles": extra.get("roles", ["集团机关层级", "分公司高层", "分公司中层"]),
        "builder_args": extra.get("builder_args", {}),
    }
    rec.update({k: v for k, v in extra.items() if k not in rec})
    return rec


ORG13 = "深圳本地13组织"
GROUP = "集团合计(剔除布吉)"

# 业务核对过的题号（共 16 题），随标准集写入 golden_dataset.json 的 business_verified 标记。
BUSINESS_VERIFIED_IDS = {
    "CX-032", "CX-033", "CX-036", "CX-037",
    "DMA-002", "DMA-026",
    "JL-016", "JL-018", "JL-019", "JL-021", "JL-022", "JL-036",
    "BJ-003", "BJ-012", "BJ-016", "BJ-017",
}
CX_CAL = "dwd_lsxt_fqcxfx；(供-售)/供，SQL 输出小数比值"

CASES = [
    C("CX-001", "本月环水集团的单月产销差率是多少？", "CX", "单月产销差率", "stat",
      "cx_group_month_rate", "single_month", "GROUP_TOTAL", "本月", GROUP, CX_CAL + "；SzwgBusiness",
      [pct("产销差率")]),
    C("CX-002", "本月环水集团的年累计产销差率是多少？", "CX", "年累计产销差率", "stat",
      "cx_group_ytd_rate", "year_month", "GROUP_TOTAL", "本月(年累计)", GROUP, CX_CAL + "；SzwgBusinessYear",
      [pct("产销差率")]),
    C("CX-003", "本月环水集团的供水量和售水量分别是多少万立方米？", "CX", "供水量、售水量", "stat",
      "cx_group_supply_sales", "single_month", "GROUP_TOTAL", "本月", GROUP, "SQL 出 m³，万立方米由评测端换算；口径=单月",
      [vol("单月供水量", "supply", aggregation="single_month", aliases=["供水量", "年累计供水量", "累计供水量"]),
       vol("单月售水量", "sales", aggregation="single_month", aliases=["售水量", "年累计售水量", "累计售水量"])]),
    C("CX-004", "本月环水集团的产销差水量（供水量减售水量）是多少立方米？", "CX", "产销差量", "stat",
      "cx_group_diff_vol", "single_month", "GROUP_TOTAL", "本月", GROUP, "SUM(供)-SUM(售)",
      [vol("产销差量", "diff_vol")]),
    C("CX-005", "本月环水集团年累计产销差率的年度目标是多少，目前与目标差距是多少？", "CX", "年度目标、目标差距", "stat",
      "cx_group_target_gap", "year_month", "GROUP_TOTAL", "本月(年累计)", GROUP, "目标=cxcndmb/100；差距=实际-目标",
      [pct("年累计产销差率", "rate", aggregation="ytd", required=False,
           aliases=["累计产销差率", "当前产销差率", "当前累计产销差率"]),
       pct("产销差率年度目标", "target_rate", aggregation="annual_target",
           aliases=["年度目标", "年度考核目标", "目标值"]),
       pp("产销差率目标差距", "gap", aggregation="actual_minus_target",
          aliases=["与目标差距", "目标差距", "低于目标", "高于目标", "差距"])]),
    C("CX-006", "本月环水集团年累计产销差率与上年同期相比，同比变动了多少？", "CX", "上年同期值、同比变化", "stat",
      "cx_group_yoy", "yoy_mom", "GROUP_TOTAL", "本月(年累计)", GROUP, "同比差=本期-同期",
      [pct("年累计产销差率上年同期值", "yoy_rate", aggregation="ytd", period_role="previous",
           aliases=["上年同期值", "去年同期", "去年同期值"]),
       pp("年累计产销差率同比变化", "yoy_change", aggregation="yoy", period_role="comparison",
          aliases=["同比变化", "同比变动"])]),
    C("CX-007", "本月环水集团单月产销差率较上月环比变动了多少？", "CX", "上月值、环比变化", "stat",
      "cx_group_mom", "single_mom", "GROUP_TOTAL", "本月(单月)", GROUP, "环比差=本月-上月，SzwgBusiness",
      [pct("本期单月产销差率", "rate", aggregation="single_month", period_role="current",
           aliases=["单月产销差率", "本月产销差率", "产销差率"]),
       pct("上期单月产销差率", "prev_rate", aggregation="single_month", period_role="previous",
           aliases=["上月值", "上月产销差率", "上期值"]),
       pp("单月产销差率环比变化", "mom_change", aggregation="mom", period_role="comparison",
          aliases=["环比变化", "环比变动", "较上月"])]),
    C("CX-008", "环水集团近6个完整月的单月产销差率分别是多少？", "CX", "单月产销差率", "detail",
      "cx_group_last6_month_rate", "last_6_months", "GROUP_TOTAL", "近6个完整月", GROUP, "SzwgBusiness 近6期",
      [pct("产销差率")], ["月份(期数)"]),
    C("CX-009", "环水集团近6个完整月的年累计产销差率分别是多少？", "CX", "年累计产销差率", "detail",
      "cx_group_last6_ytd_rate", "last_6_months", "GROUP_TOTAL", "近6个完整月", GROUP, "SzwgBusinessYear 近6期",
      [pct("产销差率")], ["月份(期数)"]),
    C("CX-010", "2026年1月至5月，环水集团每个月的年累计产销差率分别是多少？", "CX", "年累计产销差率", "detail",
      "cx_group_jan_may_ytd", "jan_may_series", "GROUP_TOTAL", "2026年1-5月", GROUP, "SzwgBusinessYear IN 1-5月",
      [pct("产销差率")], ["月份(期数)"]),
    C("CX-011", "环水集团今年上半年累计产销差率是多少？", "CX", "年累计产销差率", "stat",
      "cx_group_h1_rate", "h1", "GROUP_TOTAL", "2026年上半年(截至6月)", GROUP, "期数=当年06",
      [pct("产销差率")]),
    C("CX-012", "环水集团近6个完整月中，单月产销差率最高和最低的月份分别是哪个月，数值是多少？", "CX", "峰值/谷值月份及产销差率", "stat",
      "cx_group_last6_minmax", "last_6_months", "GROUP_TOTAL", "近6个完整月", GROUP, "单月 MAX/MIN + ym 次键",
      [cnt("最高月份", "max_ym"), pct("最高产销差率", "max_rate"), cnt("最低月份", "min_ym"), pct("最低产销差率", "min_rate")]),
    C("CX-013", "列出本月各单位的单月产销差率。", "CX", "单月产销差率", "detail",
      "cx_org_month_rate", "single_month", "SHENZHEN_LOCAL_13", "本月", ORG13, CX_CAL + "；SzwgBusiness",
      [pct("产销差率")], ["组织"]),
    C("CX-014", "列出本月各单位的年累计产销差率。", "CX", "年累计产销差率", "detail",
      "cx_org_ytd_rate", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "SzwgBusinessYear",
      [pct("产销差率")], ["组织"]),
    C("CX-015", "列出本月各单位的供水量、售水量和产销差水量明细。", "CX", "供水量、售水量、差水量", "detail",
      "cx_org_volumes", "single_month", "SHENZHEN_LOCAL_13", "本月", ORG13, "单月水量",
      [vol("供水量", "supply"), vol("售水量", "sales"), vol("产销差量", "diff_vol")], ["组织"]),
    C("CX-016", "列出本月各单位年累计产销差率及对应的年度目标。", "CX", "实际产销差率、年度目标", "detail",
      "cx_org_ytd_target", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "JOIN cxcndmb",
      [pct("实际产销差率", "rate"), pct("年度目标", "target_rate")], ["组织"]),
    C("CX-017", "列出本月各单位年累计产销差率与各自年度目标的差距（实际减目标）。", "CX", "目标差距", "detail",
      "cx_org_target_gap", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "gap=rate-target",
      [pp("目标差距", "gap")], ["组织"]),
    C("CX-018", "列出本月各单位年累计产销差率的年度目标完成率。", "CX", "完成率", "detail",
      "cx_org_completion", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "完成率=实际/目标（小数）",
      [pct("完成率", "completion")], ["组织"]),
    C("CX-019", "本月各单位中，有哪些单位的累计产销差率达到了年度目标控制要求？", "CX", "达标单位清单及产销差率", "detail",
      "cx_org_meet_target", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "低更好：rate<=target",
      [pct("产销差率")], ["组织"]),
    C("CX-020", "本月各单位中，有哪些单位的累计产销差率超过了年度目标？", "CX", "超标单位清单及产销差率", "detail",
      "cx_org_exceed_target", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "rate>target",
      [pct("产销差率")], ["组织"]),
    C("CX-021", "列出本月各单位年累计产销差率的上年同期值以及同比变化。", "CX", "上年同期、同比变化", "detail",
      "cx_org_yoy", "yoy_mom", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "同比差",
      [pct("年累计产销差率上年同期值", "yoy_rate", aggregation="ytd", period_role="previous",
           aliases=["上年同期值", "去年同期"]),
       pp("年累计产销差率同比变化", "yoy_change", aggregation="yoy", period_role="comparison",
          aliases=["同比变化", "同比变动"])], ["组织"]),
    C("CX-022", "列出本月各单位单月产销差率的上月值以及环比变化。", "CX", "上月值、环比变化", "detail",
      "cx_org_mom", "single_mom", "SHENZHEN_LOCAL_13", "本月(单月)", ORG13, "单月环比",
      [pct("上期单月产销差率", "prev_rate", aggregation="single_month", period_role="previous",
           aliases=["上月值", "上月产销差率"]),
       pp("单月产销差率环比变化", "mom_change", aggregation="mom", period_role="comparison",
          aliases=["环比变化", "环比变动"])], ["组织"]),
    C("CX-023", "本月单月产销差率最高的前三个单位是哪几家，数值是多少？", "CX", "Top 3 单位及单月产销差率", "detail",
      "cx_org_top3_month", "single_month", "SHENZHEN_LOCAL_13", "本月", ORG13, "ORDER BY rate DESC, zoneid ASC LIMIT 3",
      [pct("产销差率")], ["组织"]),
    C("CX-024", "本月年累计产销差率最低的前三个单位是哪几家，数值是多少？", "CX", "Bottom 3 单位及累计产销差率", "detail",
      "cx_org_bottom3_ytd", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "ORDER BY rate ASC, zoneid ASC LIMIT 3",
      [pct("产销差率")], ["组织"]),
    C("CX-025", "本月各单位中，年累计产销差率同比下降最多（改善最明显）的是哪家单位，降了多少？", "CX", "最大降幅单位及同比变化", "stat",
      "cx_org_max_yoy_down", "yoy_mom", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "yoy_change ASC LIMIT 1",
      [{"key": "组织", "sql_column": "org", "unit": "", "value_scale": "text"}, pp("同比变化", "yoy_change")]),
    C("CX-026", "本月各单位中，年累计产销差率同比上升最多的是哪家单位，升了多少？", "CX", "最大升幅单位及同比变化", "stat",
      "cx_org_max_yoy_up", "yoy_mom", "SHENZHEN_LOCAL_13", "本月(年累计)", ORG13, "yoy_change DESC LIMIT 1",
      [{"key": "组织", "sql_column": "org", "unit": "", "value_scale": "text"}, pp("同比变化", "yoy_change")]),
    C("CX-027", "对比本月南山分公司和宝安水务集团的年累计产销差率，哪家更低，相差多少？", "CX", "两单位累计率、差值", "stat",
      "cx_pair_ytd", "year_month", "PAIR", "本月(年累计)", "南山分公司、宝安水务", "F1003 vs F1007",
      [pct("南山分公司", "left_rate"), pct("宝安水务集团", "right_rate"), pp("差值", "gap")],
      builder_args={"left": "F1003", "right": "F1007", "left_name": "南山分公司", "right_name": "宝安水务集团"}),
    C("CX-028", "对比本月福田分公司和罗湖分公司的单月产销差率，哪家更低，相差多少？", "CX", "两单位单月率、差值", "stat",
      "cx_pair_month", "single_month", "PAIR", "本月(单月)", "福田分公司、罗湖分公司", "F1004 vs F1002",
      [pct("福田分公司", "left_rate"), pct("罗湖分公司", "right_rate"), pp("差值", "gap")],
      builder_args={"left": "F1004", "right": "F1002", "left_name": "福田分公司", "right_name": "罗湖分公司"}),
    C("CX-029", "本月南山分公司的供水量、售水量和产销差水量分别是多少？", "CX", "供水量、售水量、差水量", "stat",
      "cx_nanshan_volumes", "single_month", "F1003", "本月", "南山分公司", "zoneid=F1003 单月",
      [vol("供水量", "supply"), vol("售水量", "sales"), vol("产销差量", "diff_vol")]),
    C("CX-030", "本月盐田分公司的年累计产销差率是多少，是否达成了年度目标？", "CX", "累计率、年度目标、是否达标", "stat",
      "cx_yantian_target", "year_month", "F1001", "本月(年累计)", "盐田分公司", "met=rate<=target",
      [pct("累计产销差率", "rate"), pct("年度目标", "target_rate"), cnt("是否达标", "met")]),
    C("CX-031", "本月光明水务公司的年累计产销差率及同比变化是多少？", "CX", "累计率、同比变化", "stat",
      "cx_guangming_yoy", "yoy_mom", "F1005", "本月(年累计)", "光明水务集团", "zoneid=F1005",
      [pct("累计产销差率", "rate"), pp("同比变化", "yoy_change")]),
    C("CX-032", "2026年1月至5月，盐田分公司每个月的供水量、售水量和产销差水量分别是多少？", "CX", "月度供水、售水、差水量", "detail",
      "cx_yantian_jan_may_volumes", "jan_may_series", "F1001", "2026年1-5月", "盐田分公司", "SzwgBusiness 1-5月",
      [vol("供水量", "supply"), vol("售水量", "sales"), vol("产销差量", "diff_vol")], ["月份(期数)"]),
    C("CX-033", "2026年1月至6月，福田分公司每个月累计产销差率较上月的环比变化是多少？", "CX", "逐月累计率、逐月环比差", "detail",
      "cx_futian_jan_jun_mom", "jan_jun", "F1004", "2026年1-6月", "福田分公司", "LAG 环比，套子查询",
      [pct("累计产销差率", "rate"), pp("累计产销差率环比变化", "mom_change", aliases=["环比变化", "环比变动"])], ["月份(期数)"]),
    C("CX-034", "集团本部与深圳环境水务集团（集团行）本月的累计产销差率分别是多少？", "CX", "集团本部率、集团行列", "stat",
      "cx_benbu_vs_grouprow", "year_month", "F100_F1", "本月(年累计)", "集团本部、集团行", "zoneid IN F100,F1，禁止混入13组织",
      [pct("集团本部", "benbu_rate"), pct("深圳环境水务集团", "group_rate")]),
    C("CX-035", "剔除布吉水司后，本月集团合计的年累计产销差率是多少？", "CX", "累计产销差率", "stat",
      "cx_group_ytd_rate", "year_month", "GROUP_TOTAL", "本月(年累计)", GROUP, CX_CAL + "；同 CX-002",
      [pct("产销差率")]),
    # ===== CX-036 / CX-037（2026-09-21 补录业务核对过的 Q1 / Q3） =====
    C("CX-036", "2026年1月至5月，全集团各单位的年累计产销差率月度趋势是怎样的？", "CX", "产销差率月度趋势", "detail",
      "cx_org_jan_may_trend", "jan_may_series", "ALL_ORG_AND_TOTAL", "2026年1-5月", "全集团各单位+集团合计",
      "Q1：SzwgBusinessYear 逐月（默认年累计口径）；行=全部 zoneid 行+集团合计（剔除布吉）",
      [pct("1月", "jan"), pct("2月", "feb"), pct("3月", "mar"), pct("4月", "apr"), pct("5月", "may")], ["组织"]),
    C("CX-037", "2026上半年各单位的年累计产销差率较2025上半年同比变化是多少？", "CX", "同比分析", "detail",
      "cx_org_h1_yoy", "h1", "ALL_ORG", "2026上半年 vs 2025上半年", "全集团各单位",
      "Q3：上半年=6月年累计期数（R3）；同比=2026上半年率-2025上半年率",
      [pct("2026上半年产销差率", "rate_2026"), pct("2025上半年产销差率", "rate_2025"),
       pp("同比变化", "yoy_change")], ["组织"]),
]

LS_CAL = "dm_yyzbtx_gggsgwlsl；ljgggsgwlsl/lslndmb 百分数/100 输出小数"
LS_ORG = "深圳本地各单位"

CASES += [
    C("LS-001", "本月集团公共供水管网漏损率是多少？", "LS", "累计漏损率", "stat",
      "ls_group_ytd_rate", "year_month", "GROUP_TOTAL", "本月(年累计)", "全集团", LS_CAL, [pct("漏损率")]),
    C("LS-002", "本月集团公共供水管网漏损率的年度控制目标是多少？", "LS", "年度目标漏损率", "stat",
      "ls_group_target", "year_month", "GROUP_TOTAL", "当年", "全集团", LS_CAL, [pct("年度目标", "target_rate")]),
    C("LS-003", "本月集团公共供水管网漏损率与年度目标相比，达标了吗，差距是多少？", "LS", "实际率、目标率、差距", "stat",
      "ls_group_gap", "year_month", "GROUP_TOTAL", "本月(年累计)", "全集团", LS_CAL,
      [pct("实际漏损率", "rate"), pct("年度目标", "target_rate"), pp("漏损率目标差距", "gap", aliases=["差距", "目标差距"]), cnt("是否达标", "met")]),
    C("LS-004", "本月集团公共供水管网漏损率与去年同期相比同比变动了多少？", "LS", "去年同期率、同比变动", "stat",
      "ls_group_yoy", "yoy_mom", "GROUP_TOTAL", "本月(年累计)", "全集团", LS_CAL,
      [pct("去年同期率", "yoy_rate"), pp("同比变动", "yoy_change")]),
    C("LS-005", "本月集团公共供水管网漏损率较上月环比变动了多少？", "LS", "上月漏损率、环比变动", "stat",
      "ls_group_mom", "yoy_mom", "GROUP_TOTAL", "本月(单月/累计)", "全集团", "bygggsgwlsl 优先，空则累计",
      [pct("上月漏损率", "prev_rate"), pp("环比变动", "mom_change")]),
    C("LS-006", "集团近6个完整月的公共供水管网漏损率分别是多少？", "LS", "逐月公共供水管网漏损率", "detail",
      "ls_group_last6", "last_6_months", "GROUP_TOTAL", "近6个完整月", "全集团", LS_CAL,
      [pct("漏损率")], ["月份(期数)"]),
    C("LS-007", "2026年6月，环水集团的公共供水管网漏损率是多少？", "LS", "累计漏损率", "stat",
      "ls_fixed_202606", "fixed_202606", "GROUP_TOTAL", "2026年6月", "全集团", LS_CAL, [pct("漏损率")]),
    C("LS-008", "列出本月各单位公共供水管网漏损率及年度目标。", "LS", "实际漏损率、年度目标", "detail",
      "ls_org_rate_target", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, LS_CAL,
      [pct("实际漏损率", "rate"), pct("年度目标", "target_rate")], ["组织"]),
    C("LS-009", "列出本月各单位公共供水管网漏损率与年度目标的差距（实际减目标）。", "LS", "目标差距", "detail",
      "ls_org_gap", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "gap=rate-target",
      [pp("目标差距", "gap")], ["组织"]),
    C("LS-010", "列出本月各单位公共供水管网漏损率的上年同期值和同比变化。", "LS", "上年同期、同比变动", "detail",
      "ls_org_yoy", "yoy_mom", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, LS_CAL,
      [pct("上年同期值", "yoy_rate"), pp("同比变动", "yoy_change")], ["组织"]),
    C("LS-011", "列出本月各单位公共供水管网漏损率较上月的环比变化。", "LS", "环比变动", "detail",
      "ls_org_mom", "yoy_mom", "SHENZHEN_LOCAL_13", "本月", LS_ORG, "环比差",
      [pp("环比变动", "mom_change")], ["组织"]),
    C("LS-012", "本月公共供水管网漏损率最低的前三家单位是哪些，数值分别是多少？", "LS", "漏损率最低Top 3", "detail",
      "ls_org_bottom3", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "ASC, dwmc",
      [pct("漏损率")], ["组织"]),
    C("LS-013", "本月公共供水管网漏损率最高的前三家单位是哪些，数值分别是多少？", "LS", "漏损率最高Top 3", "detail",
      "ls_org_top3", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "DESC, dwmc",
      [pct("漏损率")], ["组织"]),
    C("LS-014", "本月各单位中，有哪些单位的供水管网漏损率满足了年度目标控制要求？", "LS", "达标单位清单及漏损率", "detail",
      "ls_org_meet", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "rate<=target",
      [pct("漏损率")], ["组织"]),
    C("LS-015", "本月各单位中，有哪些单位的供水管网漏损率超过了年度控制目标？", "LS", "超标单位清单及超标差距", "detail",
      "ls_org_exceed", "year_month", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "rate>target",
      [pct("漏损率"), pp("超标差距", "gap")], ["组织"]),
    C("LS-016", "本月各单位供水管网漏损率中，同比降幅最大的是哪家单位，下降了多少？", "LS", "最大降幅单位及同比变动", "stat",
      "ls_org_max_yoy_down", "yoy_mom", "SHENZHEN_LOCAL_13", "本月(年累计)", LS_ORG, "yoy_change ASC",
      [{"key": "组织", "sql_column": "org", "unit": "", "value_scale": "text"}, pp("同比变动", "yoy_change")]),
    C("LS-017", "本月南山分公司的公共供水管网漏损率和年度控制目标分别是多少？", "LS", "实际漏损率、年度目标", "stat",
      "ls_nanshan", "year_month", "F1003", "本月(年累计)", "南山分公司", LS_CAL,
      [pct("实际漏损率", "rate"), pct("年度目标", "target_rate")]),
    C("LS-018", "本月宝安水务集团的公共供水管网漏损率、年度目标和同比变化是多少？", "LS", "实际率、目标率、同比", "stat",
      "ls_baoan", "yoy_mom", "F1007", "本月(年累计)", "宝安水务集团", LS_CAL,
      [pct("实际漏损率", "rate"), pct("年度目标", "target_rate"), pp("同比变动", "yoy_change")]),
    C("LS-019", "对比本月南山分公司和宝安水务集团的供水管网漏损率，相差多少？", "LS", "两单位漏损率、差值", "stat",
      "ls_pair_nanshan_baoan", "year_month", "PAIR", "本月(年累计)", "南山分公司、宝安水务", "dwmc 对比",
      [pct("南山分公司", "left_rate"), pct("宝安水务集团", "right_rate"), pp("差值", "gap")]),
    C("LS-020", "对比本月福田分公司和罗湖分公司的供水管网漏损率及各自与年度目标的差距。", "LS", "两单位漏损率、目标差距", "stat",
      "ls_pair_futian_luohu", "year_month", "PAIR", "本月(年累计)", "福田分公司、罗湖分公司", "含目标差距",
      [pct("福田漏损率", "left_rate"), pp("福田差距", "left_gap"), pct("罗湖漏损率", "right_rate"), pp("罗湖差距", "right_gap")]),
    C("LS-021", "本月龙岗水务集团的公共供水管网漏损率及上年同期值分别是多少？", "LS", "实际漏损率、上年同期值", "stat",
      "ls_longgang_yoy", "yoy_mom", "F1501", "本月(年累计)", "龙岗水务集团", LS_CAL,
      [pct("实际漏损率", "rate"), pct("上年同期值", "yoy_rate")]),
    C("LS-022", "本月光明水务公司的公共供水管网漏损率是多少，是否达成年度目标？", "LS", "实际漏损率、达标判定", "stat",
      "ls_guangming_met", "year_month", "F1005", "本月(年累计)", "光明水务集团", LS_CAL,
      [pct("实际漏损率", "rate"), cnt("是否达标", "met")]),
    C("LS-023", "本月各单位中，单位管长漏损量最低的前三家单位和数值是什么？", "LS", "最优Top 3单位及管长漏损量", "detail",
      "ls_unit_pipe_loss_top3_low", "month_range", "SHENZHEN_LOCAL_13", "本月", LS_ORG,
      "单位管长漏损量=维修漏水量/(管长*天数)；water_leakage；期间=create_time",
      [{"key": "单位管长漏损量", "sql_column": "unit_loss", "unit": "m³/(km·d)", "value_scale": "volume"}], ["组织"]),
    C("LS-024", "本月各单位中，单位管长漏损量最高的前三家单位和数值是什么？", "LS", "最差Top 3单位及管长漏损量", "detail",
      "ls_unit_pipe_loss_top3_high", "month_range", "SHENZHEN_LOCAL_13", "本月", LS_ORG, "同 LS-023 DESC",
      [{"key": "单位管长漏损量", "sql_column": "unit_loss", "unit": "m³/(km·d)", "value_scale": "volume"}], ["组织"]),
    C("LS-025", "对比本月集团的年累计产销差率和公共供水管网漏损率，两者相差多少？", "LS", "累计产销差率、漏损率、差值", "stat",
      "ls_vs_cx_group", "year_month", "GROUP_TOTAL", "本月(年累计)", "全集团", "fqcxfx 与 ljgggsgwlsl",
      [pct("累计产销差率", "cx_rate"), pct("漏损率", "ls_rate"), pp("差值", "gap")]),
]

DMA_ORG = "深圳本地各单位"
DMA_CAL = "dwd_lsxt_dma + dwd_lsxt_wlls Day GOOD"

CASES += [
    C("DMA-001", "集团目前在用的居民小区 DMA 总数是多少个？", "DMA", "在用DMA小区总数", "stat",
      "dma_inuse_total", "as_of_date", "GROUP_TOTAL", "当前最新在用", "全集团台账", DMA_CAL + "；status=WORK",
      [cnt("在用DMA数", "cnt")]),
    C("DMA-002", "列出各单位目前在用的居民小区 DMA 数量及在全集团的占比。", "DMA", "各单位DMA数、占比", "detail",
      "dma_inuse_by_org", "as_of_date", "SHENZHEN_LOCAL_13", "当前最新在用", DMA_ORG, "占比=cnt/SUM(cnt)",
      [cnt("DMA数", "cnt"), pct("集团占比", "share", aliases=["占比"])], ["组织"]),
    C("DMA-003", "本月全集团有效小区 DMA 的数量是多少个？", "DMA", "有效DMA小区数", "stat",
      "dma_valid_total", "month_range", "GROUP_TOTAL", "本月", "全集团", "在用 ∩ 当月 wlls GOOD",
      [cnt("有效DMA数", "cnt")]),
    C("DMA-004", "本月全集团无效小区 DMA 的数量是多少个？", "DMA", "无效DMA小区数", "stat",
      "dma_invalid_total", "as_of_date", "GROUP_TOTAL", "本月", "全集团", "PAUSE/RETIRE",
      [cnt("无效DMA数", "cnt")]),
    C("DMA-005", "本月全集团无效小区 DMA 占总 DMA 数量的比例是多少？", "DMA", "无效DMA占比", "stat",
      "dma_invalid_share", "as_of_date", "GROUP_TOTAL", "本月", "全集团", "无效/(在用+无效)",
      [pct("无效占比", "share")]),
    C("DMA-006", "本月全集团无效小区 DMA 数量较上月环比增减了多少个？", "DMA", "无效DMA环比增减数", "stat",
      "dma_invalid_mom", "month_range", "GROUP_TOTAL", "本月", "全集团", "台账无历史，用本月无效数备注静态",
      [cnt("无效DMA数", "cnt"), cnt("上月无效数", "prev_cnt"), cnt("环比增减", "delta")]),
    C("DMA-007", "列出本月各单位 DMA 总数、无效数和无效比例。", "DMA", "DMA总数、无效数、无效占比", "detail",
      "dma_org_invalid", "as_of_date", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "总数=在用+无效",
      [cnt("DMA总数", "total_cnt"), cnt("无效数", "invalid_cnt"), pct("无效占比", "share")], ["组织"]),
    C("DMA-008", "列出本月各单位有效小区 DMA 数量及各单位有效小区总体漏损率。", "DMA", "有效DMA数、有效小区漏损率", "detail",
      "dma_org_valid_rate", "month_range", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "总体率=SUM(loss)/SUM(supply) 禁止均单位率",
      [cnt("有效DMA数", "cnt"), pct("有效小区漏损率", "rate")], ["组织"]),
    C("DMA-009", "本月全集团居民小区的总体平均漏损率是多少？", "DMA", "小区总体漏损率", "stat",
      "dma_group_rate", "month_range", "GROUP_TOTAL", "本月", "全集团有效小区", "SUM(physicalloss)/SUM(totalproduct)",
      [pct("小区总体漏损率", "rate")]),
    C("DMA-010", "本月各单位中，有效小区平均漏损率最低的前三家单位和数值是什么？", "DMA", "漏损率最低Top 3", "detail",
      "dma_org_rate_bottom3", "month_range", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "总体率 ASC",
      [pct("漏损率", "rate")], ["组织"]),
    C("DMA-011", "本月各单位中，有效小区平均漏损率最高的前三家单位是哪几家？", "DMA", "漏损率最高Top 3", "detail",
      "dma_org_rate_top3", "month_range", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "总体率 DESC",
      [pct("漏损率", "rate")], ["组织"]),
    C("DMA-012", "本月无效小区 DMA 数量最多的前三个单位是哪几家，各有多少个？", "DMA", "无效DMA最多Top 3", "detail",
      "dma_invalid_top3", "as_of_date", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "COUNT DESC, org ASC",
      [cnt("无效数", "invalid_cnt")], ["组织"]),
    C("DMA-013", "本月无效小区 DMA 占比最高的前三个单位是哪些，比例各是多少？", "DMA", "无效占比最高Top 3", "detail",
      "dma_invalid_share_top3", "as_of_date", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "share DESC",
      [pct("无效占比", "share")], ["组织"]),
    C("DMA-014", "本月漏损率超过20%的高漏耗小区共有多少个？", "DMA", "高漏耗小区总数", "stat",
      "dma_high_loss_count", "month_range", "GROUP_TOTAL", "本月", "全集团", "聚合率>=0.20",
      [cnt("高漏耗小区数", "cnt")]),
    C("DMA-015", "列出本月漏损率超过20%的高漏耗小区名单，包含小区名称、所属单位和漏损率。", "DMA", "小区名称、所属单位、漏损率", "detail",
      "dma_high_loss_list", "month_range", "GROUP_TOTAL", "本月", "漏损率>20%小区", "ORDER BY rate DESC, dmaid ASC",
      [pct("漏损率", "rate")], ["DMA编码"]),
    C("DMA-016", "本月漏损率为负数（小于0%）的小区共有多少个？", "DMA", "负漏损小区总数", "stat",
      "dma_neg_loss_count", "month_range", "GROUP_TOTAL", "本月", "全集团", "rate<0",
      [cnt("负漏损小区数", "cnt")]),
    C("DMA-017", "列出本月漏损率小于-5%的异常小区清单，列出小区名称和漏损率。", "DMA", "小区名称、漏损率", "detail",
      "dma_abnormal_neg_list", "month_range", "GROUP_TOTAL", "本月", "漏损率<-5%小区", "rate<-0.05",
      [pct("漏损率", "rate")], ["DMA编码"]),
    C("DMA-018", "本月月漏损水量大于1万立方米的小区有哪几家，各自的漏损水量是多少？", "DMA", "小区名称、漏损水量", "detail",
      "dma_loss_vol_list", "month_range", "GROUP_TOTAL", "本月", "漏损水量>1万方小区", "SUM(physicalloss)>10000",
      [vol("漏损水量", "loss_vol")], ["DMA编码"]),
    C("DMA-019", "按漏损率区间分档，本月全集团各区间的小区数量和占比各是多少？", "DMA", "各区间小区数、占比", "detail",
      "dma_bucket_group", "month_range", "GROUP_TOTAL", "本月", "全集团有效小区", "<0 / 0-10% / 10-20% / >=20%",
      [cnt("小区数", "cnt"), pct("区间占比", "share", aliases=["占比"])], ["区间"]),
    C("DMA-020", "福田分公司本月各个漏损率区间的小区数量和占比分别是多少？", "DMA", "各区间小区数、占比", "detail",
      "dma_bucket_futian", "month_range", "F1004", "本月", "福田分公司", "bz_bm 福田",
      [cnt("小区数", "cnt"), pct("区间占比", "share", aliases=["占比"])], ["区间"]),
    C("DMA-021", "南山分公司本月漏损率超过20%的小区有多少个，占该分公司有效小区的比例是多少？", "DMA", "高漏耗小区数、占比", "stat",
      "dma_nanshan_high", "month_range", "F1003", "本月", "南山分公司", "高漏耗/有效",
      [cnt("高漏耗小区数", "cnt"), pct("高漏耗占比", "share", aliases=["占比"])]),
    C("DMA-022", "本月全集团小区 DMA 的总分表偏差率是多少？", "DMA", "总分表偏差率", "stat",
      "dma_group_dev_rate", "month_range", "GROUP_TOTAL", "本月", "全集团DMA", "近似=物理漏损率（wlls）",
      [pct("总分表偏差率", "rate")]),
    C("DMA-023", "列出本月各单位小区 DMA 的总分表偏差率。", "DMA", "总分表偏差率", "detail",
      "dma_org_dev_rate", "month_range", "SHENZHEN_LOCAL_13", "本月", DMA_ORG, "按组织聚合物理漏损率",
      [pct("总分表偏差率", "rate")], ["组织"]),
    C("DMA-024", "对比本月南山分公司和宝安水务集团的无效小区 DMA 比例，哪家更低？", "DMA", "两单位无效占比、差值", "stat",
      "dma_pair_invalid", "as_of_date", "PAIR", "本月", "南山分公司、宝安水务", "无效占比对比",
      [pct("南山无效占比", "left_share"), pct("宝安无效占比", "right_share"), pp("差值", "gap")]),
    C("DMA-025", "对比本月南山分公司和宝安水务集团的有效小区平均漏损率，相差多少？", "DMA", "两单位漏损率、差值", "stat",
      "dma_pair_rate", "month_range", "PAIR", "本月", "南山分公司、宝安水务", "总体率对比",
      [pct("南山漏损率", "left_rate"), pct("宝安漏损率", "right_rate"), pp("差值", "gap")]),
    # ===== DMA-026（2026-09-21 补录业务核对过的 Q28）：产销差率 × DMA 漏损量关联 =====
    C("DMA-026", "各单位2026年6月的DMA漏损量、DMA小区数及上半年产销差率分别是多少？", "DMA", "产销差率、DMA漏损量、DMA小区数", "detail",
      "dma_org_cx_loss", "fixed_202606", "SHENZHEN_LOCAL_13", "漏损量2026年6月、产销差率2026上半年", "各分公司/水司",
      "Q28：漏损量=DMA（wlls Day/GOOD）月合计；不做单DMA平均漏损（R11）；明确月份",
      [pct("累计产销差率", "rate"), vol("DMA漏损量", "loss_vol"), cnt("DMA小区数", "dma_cnt")], ["组织"]),
]

JL_ORG = "各分公司/水司"
JL_YTD = "dm_lszb_tlxl_tj 年累计；排除本地/其他"

CASES += [
    C("JL-001", "今年以来，集团供水管道维修工单总数是多少单？", "JL", "管道维修工单总数", "stat",
      "jl_group_repair_cnt", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团", JL_YTD,
      [cnt("维修工单数", "cnt")]),
    C("JL-002", "今年以来，集团供水管道每公里平均维修单数是多少单/公里？", "JL", "每公里维修单数", "stat",
      "jl_group_repair_per_km", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团", "SUM(gsgdwxgds)/SUM(gdcd)",
      [per_km("每公里维修单数", "per_km")]),
    C("JL-003", "今年以来，集团供水管道维修工单总数与去年同期相比同比变化是多少？", "JL", "同期工单数、同比变化", "stat",
      "jl_group_repair_yoy", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团", "同比=(今年-去年)/去年",
      [cnt("同期工单数", "yoy_cnt"), pct("同比变化", "yoy_change")]),
    C("JL-004", "今年以来，集团管网检漏工单总数是多少单？", "JL", "检漏工单总数", "stat",
      "jl_group_detect_cnt", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团", "SUM(jlwxgds)",
      [cnt("检漏工单数", "cnt")]),
    C("JL-005", "今年以来，集团管网每公里检漏单数是多少单/公里？", "JL", "每公里检漏单数", "stat",
      "jl_group_detect_per_km", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团", "SUM(jlwxgds)/SUM(gdcd)",
      [per_km("每公里检漏单数", "per_km")]),
    C("JL-006", "今年以来，集团整体的检漏效率是多少？", "JL", "检漏效率", "stat",
      "jl_group_efficiency", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团汇总", "jlmx 完工率=COUNT(finish)/COUNT(*)",
      [pct("检漏效率", "rate")]),
    C("JL-007", "今年集团整体检漏效率与去年同期相比变化了多少？", "JL", "同期检漏效率、同比变动", "stat",
      "jl_group_efficiency_yoy", "ytd_range", "GROUP_TOTAL", "当年累计", "全集团汇总", "两年完工率差",
      [pct("同期检漏效率", "yoy_rate"), pp("同比变动", "yoy_change")]),
    C("JL-008", "列出今年各单位供水管道维修工单总数及每公里维修单数。", "JL", "维修单数、每公里单数", "detail",
      "jl_org_repair", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, JL_YTD,
      [cnt("维修工单数", "cnt"), per_km("每公里维修单数", "per_km")], ["组织"]),
    C("JL-009", "列出今年各单位管网检漏工单总数及每公里检漏单数。", "JL", "检漏单数、每公里单数", "detail",
      "jl_org_detect", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, JL_YTD,
      [cnt("检漏工单数", "cnt"), per_km("每公里检漏单数", "per_km")], ["组织"]),
    C("JL-010", "列出今年各单位的检漏效率及对应同比变化。", "JL", "检漏效率、同比变动", "detail",
      "jl_org_efficiency", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "jlxl/100",
      [pct("检漏效率", "rate"), pp("同比变动", "yoy_change")], ["组织"]),
    C("JL-011", "今年各单位中，检漏效率最高的前三家单位和数值是什么？", "JL", "检漏效率最高Top 3", "detail",
      "jl_org_eff_top3", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "DESC",
      [pct("检漏效率", "rate")], ["组织"]),
    C("JL-012", "今年各单位中，检漏效率最低的三家单位分别是哪几家，数值是多少？", "JL", "检漏效率最低Top 3", "detail",
      "jl_org_eff_bottom3", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "ASC",
      [pct("检漏效率", "rate")], ["组织"]),
    C("JL-013", "今年供水管道维修工单总数最多的三个单位是哪几家，各有多少单？", "JL", "维修工单最多Top 3", "detail",
      "jl_org_repair_top3", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "gsgdwxgds DESC",
      [cnt("维修工单数", "cnt")], ["组织"]),
    C("JL-014", "今年每公里管道维修单数最高的三个单位是哪些，分别是多少？", "JL", "每公里单数最高Top 3", "detail",
      "jl_org_repair_per_km_top3", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "per_km DESC",
      [per_km("每公里维修单数", "per_km")], ["组织"]),
    C("JL-015", "今年检漏工单总数排名前三的单位各完成了多少单？", "JL", "检漏工单最多Top 3", "detail",
      "jl_org_detect_top3", "ytd_range", "SHENZHEN_LOCAL_13", "当年累计", JL_ORG, "jlwxgds DESC",
      [cnt("检漏工单数", "cnt")], ["组织"]),
    C("JL-016", "上月各单位供水管道维修工单记录的漏损水量合计是多少立方米？", "JL", "维修漏损水量", "detail",
      "jl_org_leakage", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", JL_ORG, "只使用 water_leakage（R7）；期间=create_time",
      [vol("维修漏损水量", "loss_vol", aliases=[
          "维修漏损水量", "维修工单漏损水量", "供水管道维修工单漏损水量", "工单漏损水量",
          "漏损水量", "漏损水量(m³)", "漏损量", "loss_vol"])], ["组织"]),
    C("JL-017", "上月集团消防栓维修工单总数是多少单？", "JL", "消防栓维修工单数", "stat",
      "jl_hydrant_cnt", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "create_time 半开区间（GD-009）；dwd_gdgl_gd_xfswxmx",
      [cnt("消防栓维修工单数", "cnt")]),
    C("JL-018", "列出上月各单位消防栓维修工单数量、排放水量和漏失水量合计。", "JL", "维修单数、排放水量、漏失水量", "detail",
      "jl_org_hydrant", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", JL_ORG, "discharge_water 与 water_leakage 分列（GD-010/011）；期间=create_time",
      [cnt("维修单数", "cnt"), vol("排放水量", "discharge"), vol("漏失水量", "loss_vol")], ["组织"]),
    C("JL-019", "上月创建的最新10条检漏工单分别是哪些？列出工单编号、所属单位、标题和创建时间。", "JL", "最新10条工单明细", "detail",
      "jl_latest10", "prev_month_range", "GROUP_TOTAL", "上月最新10条", "全集团", "ORDER BY create_time DESC, id ASC LIMIT 10",
      [{"key": "工单编号", "sql_column": "id", "unit": "", "value_scale": "text"}], ["工单编号"]),
    C("JL-020", "上月集团检漏工单从创建到首次到场的平均响应时间是多少小时？", "JL", "平均响应小时数", "stat",
      "jl_group_response", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "arrive_time 非空",
      [hour("平均响应小时数", "hours")]),
    C("JL-021", "上月各单位有到场记录的检漏工单平均响应时间分别是多少小时？", "JL", "各单位平均响应小时数", "detail",
      "jl_org_response", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", JL_ORG, "按组织 AVG",
      [hour("平均响应小时数", "hours")], ["组织"]),
    C("JL-022", "上月各单位检漏工单完成率对标情况如何？列出各单位工单总数、完成数和完成率。", "JL", "工单总数、完成数、完成率", "detail",
      "jl_org_complete", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", JL_ORG, "完工判定=finish_time 非空；期间=create_time",
      [cnt("工单总数", "total_cnt"), cnt("完成数", "fin_cnt"), pct("完成率", "rate")], ["组织"]),
    C("JL-023", "本月集团管网维抢修45分钟到场及时率是多少？", "JL", "45分钟到场及时率", "stat",
      "jl_arrive_intime", "month_range", "GROUP_TOTAL", "本月", "全集团", "arrive_intime='是'/arrive_time 非空；期间=create_time（GD-006）",
      [pct("45分钟到场及时率", "rate")]),
    C("JL-024", "本月集团管网维抢修8小时修复及时率是多少？", "JL", "8小时修复及时率", "stat",
      "jl_repair_8h", "month_range", "GROUP_TOTAL", "本月", "全集团", "finish-start_repair<=8h；期间=create_time",
      [pct("8小时修复及时率", "rate")]),
    C("JL-025", "对比南山分公司和宝安水务集团今年的管道维修单数、检漏工单数及检漏效率。", "JL", "维修单数、检漏单数、检漏效率", "stat",
      "jl_pair_nanshan_baoan", "ytd_range", "PAIR", "当年累计", "南山分公司、宝安水务", "tlxl 两单位",
      [cnt("南山维修单数", "left_repair"), cnt("南山检漏单数", "left_detect"), pct("南山检漏效率", "left_rate"),
       cnt("宝安维修单数", "right_repair"), cnt("宝安检漏单数", "right_detect"), pct("宝安检漏效率", "right_rate")]),
    # ===== JL-026~JL-035：维修工单基础统计（期间=create_time 半开区间） =====
    C("JL-026", "本月集团供水管道维修工单总数是多少单？", "JL", "管道维修工单总数", "stat",
      "jl_repair_cnt", "month_range", "GROUP_TOTAL", "本月", "全集团",
      "工单期间=create_time 半开区间（GD-001）；dwd_gdgl_gd_gsgdwxmx",
      [cnt("维修工单数", "cnt")]),
    C("JL-027", "列出本月各单位供水管道维修工单数量。", "JL", "各单位维修工单数", "detail",
      "jl_repair_by_org", "month_range", "SHENZHEN_LOCAL_13", "本月", JL_ORG,
      "create_time + bz_bm 分组（GD-001）",
      [cnt("维修工单数", "cnt")], ["组织"]),
    C("JL-028", "环水集团近6个完整月的供水管道维修工单数量分别是多少？", "JL", "月度维修工单数", "detail",
      "jl_repair_last6", "last_6_months", "GROUP_TOTAL", "近6个完整月", "全集团",
      "create_time 月份分组（GD-001）",
      [cnt("维修工单数", "cnt")], ["月份(期数)"]),
    C("JL-029", "本月集团阀门维修工单总数是多少单？", "JL", "阀门维修工单数", "stat",
      "jl_valve_cnt", "month_range", "GROUP_TOTAL", "本月", "全集团",
      "create_time 半开区间；dwd_gdgl_gd_fmwxgdmx",
      [cnt("维修工单数", "cnt")]),
    C("JL-030", "列出本月各单位阀门维修工单数量。", "JL", "各单位阀门维修工单数", "detail",
      "jl_valve_by_org", "month_range", "SHENZHEN_LOCAL_13", "本月", JL_ORG,
      "create_time + bz_bm 分组；fmwxgdmx",
      [cnt("维修工单数", "cnt")], ["组织"]),
    C("JL-031", "本月集团消防栓维修工单总数是多少单？", "JL", "消防栓维修工单数", "stat",
      "jl_hydrant_cnt", "month_range", "GROUP_TOTAL", "本月", "全集团",
      "create_time 半开区间（GD-009）；dwd_gdgl_gd_xfswxmx",
      [cnt("消防栓维修工单数", "cnt")]),
    C("JL-032", "列出本月各单位消防栓维修工单数量。", "JL", "各单位消防栓维修工单数", "detail",
      "jl_hydrant_by_org", "month_range", "SHENZHEN_LOCAL_13", "本月", JL_ORG,
      "create_time + bz_bm 分组；xfswxmx",
      [cnt("维修工单数", "cnt")], ["组织"]),
    C("JL-033", "本月集团供水管道、阀门和消防栓维修工单各有多少单？", "JL", "三类维修工单数", "stat",
      "jl_three_split", "month_range", "GROUP_TOTAL", "本月", "全集团",
      "三表各自 create_time 半开区间",
      [cnt("供水管道维修工单数", "repair_cnt"), cnt("阀门维修工单数", "valve_cnt"),
       cnt("消防栓维修工单数", "hydrant_cnt")]),
    C("JL-034", "本月集团三类维修工单（供水管道、阀门、消防栓）合计多少单？", "JL", "三类维修工单合计", "stat",
      "jl_three_total", "month_range", "GROUP_TOTAL", "本月", "全集团",
      "三表合计 create_time 半开区间",
      [cnt("维修工单数", "cnt")]),
    C("JL-035", "本月集团供水管道维修工单总数较上月环比变动了多少？", "JL", "本期、上期、环比变化", "stat",
      "jl_repair_mom", "month_range", "GROUP_TOTAL", "本月(环比)", "全集团",
      "create_time 半开区间；环比=(本月-上月)/上月",
      [cnt("本期维修工单数", "cnt"), cnt("上期维修工单数", "prev_cnt"),
       pct("维修工单数环比变化", "mom_change")]),
    # ===== JL-036（2026-09-21 补录业务核对过的 Q30）：产销差率 × 检漏工单数 =====
    C("JL-036", "列出各单位2026年6月单月产销差率和2026年7月检漏工单数量。", "JL", "产销差率、检漏工单数", "detail",
      "jl_org_cx_detect", "fixed_202606", "SHENZHEN_LOCAL_13", "产销差率2026年6月、工单2026年7月", "各分公司/水司",
      "Q30：产销差率=SzwgBusiness 202606；工单=jlmx create_time 2026-07；工单类型明确为检漏；无每单平均产销差（R12）",
      [pct("单月产销差率", "rate"), cnt("检漏工单数", "detect_cnt")], ["组织"]),
]

BJ_ORG = "各分公司/水司"

CASES += [
    C("BJ-001", "上月全集团产生的居民小区夜间小流量预警总次数是多少次？", "BJ", "预警总次数", "stat",
      "bj_nightflow_cnt", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "srctype=NightFlow；bz_bm 禁止 zonename",
      [cnt("预警次数", "cnt")]),
    C("BJ-002", "列出上月各单位夜间小流量预警的次数分布。", "BJ", "预警次数", "detail",
      "bj_nightflow_by_org", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", BJ_ORG, "ORG_MAP_SQL",
      [cnt("预警次数", "cnt")], ["组织"]),
    C("BJ-003", "上月夜间小流量预警频次最高的前10个小区 DMA 分别是哪些？列出编码、名称、单位和预警次数。", "BJ", "Top 10 预警小区及次数", "detail",
      "bj_nightflow_top10", "prev_month_range", "GROUP_TOTAL", "上月", "全集团DMA", "ORDER BY cnt DESC, dmaid ASC LIMIT 10",
      [cnt("预警次数", "cnt")], ["DMA编码"]),
    C("BJ-004", "上月集团夜间小流量预警的总处置率是多少？", "BJ", "处置率", "stat",
      "bj_handle_rate", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "handled=true AND handldate IS NOT NULL",
      [pct("处置率", "rate")]),
    C("BJ-005", "上月集团夜间小流量预警中，已处置和未处置的工单数各是多少单？", "BJ", "预警总数、已处置数、未处置数", "stat",
      "bj_handle_split", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "分列计数",
      [cnt("预警总数", "total_cnt"), cnt("已处置数", "handled_cnt"), cnt("未处置数", "open_cnt")]),
    C("BJ-006", "截至目前，上月产生的夜间小流量预警中超期仍未处置的有多少单？", "BJ", "超期未处置单数", "stat",
      "bj_overdue", "prev_month_range", "GROUP_TOTAL", "上月产生且至今未处置", "全集团", "未闭环且 warndate 超过24小时",
      [cnt("超期未处置单数", "cnt")]),
    C("BJ-007", "昨日全集团哪些小区 DMA 出现了夜间小流量异常？列出小区名称和单位。", "BJ", "异常小区名单", "detail",
      "bj_yesterday_list", "yesterday", "GROUP_TOTAL", "昨日", "全集团", "warndate::date=:start_date",
      [cnt("预警次数", "cnt")], ["DMA编码"]),
    C("BJ-008", "上月集团发生的供水管网爆管事件总数是多少起？", "BJ", "爆管总次数", "stat",
      "bj_burst_cnt", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "accident_type LIKE 爆 或 flow_status_name LIKE 爆管（GD-008）；期间=create_time",
      [cnt("爆管次数", "cnt")]),
    C("BJ-009", "列出上月各单位发生的爆管事件数量。", "BJ", "爆管事件数", "detail",
      "bj_burst_by_org", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", BJ_ORG, "按组织 COUNT；期间=create_time",
      [cnt("爆管次数", "cnt")], ["组织"]),
    C("BJ-010", "按管径分段（不足400、400至不足600、600至不足1000、1000毫米及以上），上月爆管事件各发生了多少起？", "BJ", "各管径段爆管起数", "detail",
      "bj_burst_caliber", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "caliber 分段；期间=create_time",
      [cnt("爆管次数", "cnt")], ["管径分段"]),
    C("BJ-011", "上月发生的爆管事件中，平均管径是多少毫米？", "BJ", "平均管径、样本数", "stat",
      "bj_burst_avg_caliber", "prev_month_range", "GROUP_TOTAL", "上月", "全集团有效管径事件", "caliber 可转 numeric；期间=create_time",
      [{"key": "平均管径", "sql_column": "avg_caliber", "unit": "mm", "value_scale": "volume"}, cnt("样本数", "sample_cnt")]),
    C("BJ-012", "截至基准日，今年内各单位反复维修超过2次的供水管道有哪些？列出管道编码、单位、地址和维修次数。", "BJ", "管道编码、单位、地址、维修次数", "detail",
      "bj_repeat_pipe", "ytd_range", "SHENZHEN_LOCAL_13", "当年截至基准日", "反复维修管道(>2次)", "GROUP BY 管道编码 HAVING COUNT>2；期间=create_time；地址=detailedaddress（R9）",
      [cnt("维修次数", "cnt")], ["管道编码"]),
    C("BJ-013", "5月至7月期间，维修次数排名前5的管道设施编码和维修次数分别是什么？", "BJ", "管道编码、维修次数", "detail",
      "bj_top5_pipe", "may_jul_range", "GROUP_TOTAL", "5-7月", "前5名管道", "gsgdwxmx；期间=create_time",
      [cnt("维修次数", "cnt")], ["设施编码"]),
    C("BJ-014", "5月至7月期间，维修次数排名前5的阀门设施编码和维修次数分别是什么？", "BJ", "阀门编码、维修次数", "detail",
      "bj_top5_valve", "may_jul_range", "GROUP_TOTAL", "5-7月", "前5名阀门", "fmwxgdmx；期间=create_time",
      [cnt("维修次数", "cnt")], ["设施编码"]),
    C("BJ-015", "5月至7月期间，维修次数排名前5的消防栓设施编码和维修次数分别是什么？", "BJ", "消防栓编码、维修次数", "detail",
      "bj_top5_hydrant", "may_jul_range", "GROUP_TOTAL", "5-7月", "前5名消防栓", "xfswxmx；期间=create_time",
      [cnt("维修次数", "cnt")], ["设施编码"]),
    # ===== BJ-016 / BJ-017（2026-09-21 补录业务核对过的 Q19 / Q35 下钻） =====
    C("BJ-016", "上月产生的漏损预警中，预警总数、未处理数和超过10天未处理数分别是多少？", "BJ", "预警总数、未处理数、超时未处理数", "stat",
      "bj_overdue_10d", "prev_month_range", "GROUP_TOTAL", "上月", "全集团", "R6：超时=漏损预警10天内未处理（不限 srctype）；观察点=月末",
      [cnt("预警总数", "total_cnt"), cnt("未处理数", "unhandled_cnt"), cnt("超时未处理数", "overdue_cnt")]),
    C("BJ-017", "按管径分段列出上月爆管事件在各单位的发生情况，并下钻到三级部门。", "BJ", "管径分段、单位、三级部门、爆管次数", "detail",
      "bj_burst_caliber_org", "prev_month_range", "SHENZHEN_LOCAL_13", "上月", "各分公司及三级部门",
      "Q35：爆管=accident_type 含爆（GD-008 等价条件）；管径分段；分公司+水务所下钻（R10）",
      [cnt("爆管次数", "cnt")], ["管径分段", "组织", "三级部门"]),
]
